/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#ffb2bf",
        "on-surface-variant": "#d8c1c3",
        "surface-container-high": "#282a2e",
        "outline": "#a08c8e",
        "on-surface": "#e2e2e8",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#0c0e12",
        "tertiary-fixed-dim": "#ffb2bf",
        "on-tertiary-container": "#651d31",
        "secondary-fixed": "#ffd9df",
        "surface-variant": "#333539",
        "on-tertiary-fixed": "#3f0015",
        "tertiary": "#ffb2bf",
        "primary-container": "#e08798",
        "on-primary-fixed-variant": "#753040",
        "error": "#ffb4ab",
        "surface-dim": "#111317",
        "on-primary-container": "#622131",
        "primary": "#ffb2bf",
        "on-error": "#690005",
        "secondary-container": "#6f3443",
        "primary-fixed-dim": "#ffb2bf",
        "surface-container": "#1e2024",
        "inverse-on-surface": "#2f3035",
        "on-primary": "#591a2a",
        "primary-fixed": "#ffd9de",
        "on-background": "#e2e2e8",
        "on-secondary": "#531e2d",
        "on-tertiary-fixed-variant": "#792d3f",
        "surface-container-highest": "#333539",
        "tertiary-container": "#e68497",
        "tertiary-fixed": "#ffd9de",
        "surface-container-low": "#1a1c20",
        "inverse-primary": "#924757",
        "surface-bright": "#37393e",
        "on-secondary-container": "#ee9faf",
        "on-tertiary": "#5c1629",
        "secondary-fixed-dim": "#ffb1c1",
        "inverse-surface": "#e2e2e8",
        "on-primary-fixed": "#3d0416",
        "background": "#111317",
        "error-container": "#93000a",
        "surface": "#111317",
        "secondary": "#ffb1c1",
        "on-secondary-fixed-variant": "#6f3443",
        "outline-variant": "#534345",
        "on-secondary-fixed": "#390918"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "gutter": "1.25rem",
        "space-sm": "0.5rem",
        "space-xl": "2rem",
        "margin": "1rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "margin-desktop": "2rem",
        "gutter-desktop": "1.5rem",
        "space-lg": "1.5rem"
      },
      fontFamily: {
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "display-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }]
      }
    }
  },
  plugins: [],
}
